package common;

public enum Mission {
	GET_SUBSCRIBERS("GET_SUBSCRIBERS", 0), 
	EDIT_SUBSCRIBERS_DATA("EDIT_SUBSCRIBERS_DATA", 1),
	SEND_CONNECTION_DETAILS("SEND_CONNECTION_DETAILS", 2),
	SEND_DISCONNECTION_DETAILS("SEND_DISCONNECTION_DETAILS", 3),
	IDENTIFY_USER("IDENTIFY_USER", 4),
	ADD_CUSTOMER_DATA("ADD_CUSTOMER_DATA",5),
	FROM_CUSTOMER_TO_SUBSCRIBER("FROM_CUSTOMER_TO_SUBSCRIBER",6);
	

	private Mission(final String mission, final int serialNumber) {
	}
}
